-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  description text NOT NULL,
  type text NOT NULL,
  icon text NOT NULL,
  points integer DEFAULT 0,
  unlocked_at timestamp with time zone DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  check_in_time timestamp with time zone NOT NULL,
  check_out_time timestamp with time zone,
  duration_minutes integer,
  attendance_date date DEFAULT CURRENT_DATE,
  gym_id uuid,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT attendance_gym_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.cash_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  gym_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  receipt_number text NOT NULL UNIQUE,
  payment_date timestamp with time zone DEFAULT now(),
  received_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subscription_id uuid,
  pending_payment_id uuid,
  installment_id uuid,
  invoice_id uuid,
  CONSTRAINT cash_payments_pkey PRIMARY KEY (id),
  CONSTRAINT cash_payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.razorpay_subscriptions(id),
  CONSTRAINT cash_payments_pending_payment_id_fkey FOREIGN KEY (pending_payment_id) REFERENCES public.pending_payments(id),
  CONSTRAINT cash_payments_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES public.payment_installments(id),
  CONSTRAINT cash_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.diet_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  meal_name text NOT NULL,
  meal_type text NOT NULL CHECK (meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text, 'snack'::text])),
  calories numeric NOT NULL,
  protein numeric DEFAULT 0,
  carbs numeric DEFAULT 0,
  fat numeric DEFAULT 0,
  log_date date DEFAULT CURRENT_DATE,
  logged_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diet_logs_pkey PRIMARY KEY (id),
  CONSTRAINT diet_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.diet_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid,
  name text NOT NULL,
  description text,
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  meal_type text CHECK (meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text, 'snack'::text, 'pre-workout'::text, 'post-workout'::text])),
  meal_name text NOT NULL,
  calories numeric,
  protein numeric,
  carbs numeric,
  fat numeric,
  ingredients ARRAY,
  instructions text,
  is_personal boolean DEFAULT false,
  personal_training_id uuid,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diet_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['workout'::text, 'streak'::text, 'calories'::text, 'diet'::text, 'attendance'::text])),
  target_value integer NOT NULL,
  xp_reward integer NOT NULL DEFAULT 50,
  icon text NOT NULL DEFAULT '🎯'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT goals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gym_owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  gym_name text NOT NULL,
  gym_address text,
  gym_city text,
  gym_state text,
  gym_pincode text,
  razorpay_account_id text UNIQUE,
  razorpay_account_status text DEFAULT 'not_created'::text,
  onboarding_link text,
  onboarding_completed boolean DEFAULT false,
  onboarding_completed_at timestamp with time zone,
  kyc_status text DEFAULT 'pending'::text,
  kyc_verified_at timestamp with time zone,
  business_type text,
  business_name text,
  gstin text,
  pan text,
  commission_percentage numeric DEFAULT 10.00,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_owners_pkey PRIMARY KEY (id),
  CONSTRAINT gym_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.gym_payment_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gym_id uuid NOT NULL UNIQUE,
  razorpay_account_id text,
  razorpay_key_id text,
  razorpay_key_secret text,
  bank_account_number text,
  bank_ifsc_code text,
  bank_name text,
  account_holder_name text,
  upi_id text,
  payment_gateway text DEFAULT 'razorpay'::text CHECK (payment_gateway = ANY (ARRAY['razorpay'::text, 'bank_transfer'::text, 'upi'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_payment_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gym_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value text NOT NULL,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gym_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gyms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text,
  phone text,
  email text,
  description text,
  logo_url text,
  owner_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gyms_pkey PRIMARY KEY (id),
  CONSTRAINT gyms_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_number text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  gym_id uuid,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['cash'::text, 'online'::text, 'razorpay'::text])),
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  tax_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  payment_status text DEFAULT 'paid'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'completed'::text])),
  invoice_date timestamp with time zone DEFAULT now(),
  due_date date,
  items jsonb,
  payment_id text,
  subscription_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_installment boolean DEFAULT false,
  installment_number integer,
  total_installments integer,
  parent_invoice_id uuid,
  original_total_amount numeric,
  remaining_amount numeric DEFAULT 0,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT invoices_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT invoices_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id),
  CONSTRAINT invoices_parent_invoice_id_fkey FOREIGN KEY (parent_invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.owner_subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL,
  currency text NOT NULL DEFAULT 'INR'::text,
  billing_cycle text NOT NULL DEFAULT 'monthly'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'yearly'::text])),
  duration_days integer NOT NULL,
  features jsonb DEFAULT '[]'::jsonb,
  member_limit integer,
  trainer_limit integer,
  storage_limit_mb integer,
  trial_days integer DEFAULT 0,
  razorpay_plan_id text UNIQUE,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT owner_subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.owner_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  gym_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  start_date timestamp with time zone NOT NULL DEFAULT now(),
  end_date timestamp with time zone NOT NULL,
  trial_end_date timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'expired'::text, 'cancelled'::text, 'suspended'::text, 'trial'::text])),
  razorpay_subscription_id text UNIQUE,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  payment_status text NOT NULL DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'refunded'::text])),
  amount_paid numeric DEFAULT 0,
  last_payment_date timestamp with time zone,
  next_billing_date date,
  auto_renew boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  CONSTRAINT owner_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT owner_subscriptions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT owner_subscriptions_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT owner_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.owner_subscription_plans(id)
);
CREATE TABLE public.password_reset_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  used boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_installments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pending_payment_id uuid NOT NULL,
  installment_number integer NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['cash'::text, 'online'::text, 'razorpay'::text])),
  payment_date timestamp with time zone,
  receipt_number text,
  razorpay_order_id text,
  razorpay_payment_id text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invoice_id uuid,
  user_id uuid,
  gym_id uuid,
  CONSTRAINT payment_installments_pkey PRIMARY KEY (id),
  CONSTRAINT payment_installments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payment_installments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payment_installments_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  razorpay_subscription_id uuid,
  plan_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  payment_method text DEFAULT 'razorpay'::text,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'refunded'::text])),
  payment_date timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payments_razorpay_subscription_id_fkey FOREIGN KEY (razorpay_subscription_id) REFERENCES public.razorpay_subscriptions(id),
  CONSTRAINT payments_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.payments_unified (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  gym_id uuid,
  amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'online'::text, 'razorpay'::text, 'bank_transfer'::text, 'upi'::text])),
  payment_type text CHECK (payment_type = ANY (ARRAY['subscription'::text, 'installment'::text, 'renewal'::text, 'refund'::text, 'adjustment'::text])),
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  receipt_number text,
  received_by uuid,
  is_installment boolean DEFAULT false,
  installment_number integer,
  total_installments integer,
  parent_payment_id uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'refunded'::text, 'cancelled'::text])),
  payment_date timestamp with time zone,
  invoice_id uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_unified_pkey PRIMARY KEY (id),
  CONSTRAINT payments_unified_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payments_unified_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id),
  CONSTRAINT payments_unified_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT payments_unified_received_by_fkey FOREIGN KEY (received_by) REFERENCES auth.users(id),
  CONSTRAINT payments_unified_parent_payment_id_fkey FOREIGN KEY (parent_payment_id) REFERENCES public.payments_unified(id),
  CONSTRAINT payments_unified_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gym_owner_id uuid,
  razorpay_account_id text NOT NULL,
  amount integer NOT NULL,
  currency text DEFAULT 'INR'::text,
  razorpay_payout_id text UNIQUE,
  razorpay_fund_account_id text,
  status text DEFAULT 'pending'::text,
  purpose text DEFAULT 'payout'::text,
  initiated_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  error_code text,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_gym_owner_id_fkey FOREIGN KEY (gym_owner_id) REFERENCES public.gym_owners(id)
);
CREATE TABLE public.pending_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  gym_id uuid,
  total_amount numeric NOT NULL,
  paid_amount numeric DEFAULT 0,
  pending_amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  due_date date NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'overdue'::text])),
  notes text,
  subscription_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invoice_id uuid,
  plan_id uuid,
  CONSTRAINT pending_payments_pkey PRIMARY KEY (id),
  CONSTRAINT pending_payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.razorpay_subscriptions(id),
  CONSTRAINT pending_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT pending_payments_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.personal_training_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  gym_id uuid,
  assigned_by uuid,
  is_active boolean DEFAULT true,
  start_date date NOT NULL,
  end_date date,
  fee_amount numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT personal_training_assignments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  duration_days integer NOT NULL,
  features jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gym_id uuid,
  is_global boolean DEFAULT false,
  CONSTRAINT plans_pkey PRIMARY KEY (id),
  CONSTRAINT plans_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gym_owners(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['admin'::text, 'member'::text, 'gym_owner'::text])),
  phone text,
  gym_id uuid,
  level integer DEFAULT 1,
  total_points integer DEFAULT 0,
  current_streak integer DEFAULT 0,
  max_streak integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gym_joined_at timestamp with time zone,
  has_personal_training boolean DEFAULT false,
  weight numeric,
  height numeric,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_gym_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.razorpay_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'pending'::text])),
  start_date timestamp with time zone NOT NULL DEFAULT now(),
  end_date timestamp with time zone NOT NULL,
  auto_renew boolean DEFAULT false,
  razorpay_subscription_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gym_id uuid,
  CONSTRAINT razorpay_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT razorpay_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT razorpay_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.razorpay_webhooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  event_id text NOT NULL UNIQUE,
  razorpay_account_id text,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT razorpay_webhooks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.route_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  razorpay_payment_id text NOT NULL,
  razorpay_order_id text NOT NULL,
  gym_owner_id uuid,
  razorpay_account_id text NOT NULL,
  total_amount integer NOT NULL,
  gym_owner_amount integer NOT NULL,
  platform_commission integer DEFAULT 0,
  razorpay_transfer_id text,
  transfer_status text DEFAULT 'pending'::text,
  transfer_created_at timestamp with time zone,
  transfer_processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT route_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT route_transactions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT route_transactions_gym_owner_id_fkey FOREIGN KEY (gym_owner_id) REFERENCES public.gym_owners(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  duration_months integer NOT NULL DEFAULT 1,
  duration_days integer NOT NULL DEFAULT 0,
  price numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  features jsonb DEFAULT '[]'::jsonb,
  gym_id uuid,
  created_by uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT subscriptions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  goal_id uuid,
  current_progress integer DEFAULT 0,
  target_value integer NOT NULL,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  xp_earned integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_goals_pkey PRIMARY KEY (id),
  CONSTRAINT user_goals_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  subscription_id uuid,
  start_date date DEFAULT CURRENT_DATE,
  end_date date,
  payment_status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  amount_paid numeric DEFAULT 0,
  payment_method text,
  payment_date timestamp with time zone,
  auto_renew boolean DEFAULT false,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  currency text DEFAULT 'INR'::text,
  gym_id uuid,
  total_amount numeric,
  paid_amount numeric,
  pending_amount numeric,
  discount_amount numeric DEFAULT 0,
  payment_type text CHECK (payment_type = ANY (ARRAY['cash'::text, 'online'::text, 'razorpay'::text])),
  razorpay_subscription_id text,
  razorpay_order_id text,
  razorpay_payment_id text,
  allow_installments boolean DEFAULT false,
  total_installments integer DEFAULT 1,
  completed_installments integer DEFAULT 0,
  status text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'pending'::text, 'suspended'::text])),
  due_date date,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_by uuid,
  last_payment_date timestamp with time zone,
  next_billing_date date,
  payment_notes text,
  custom_start_date date,
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_subscriptions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT user_subscriptions_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id),
  CONSTRAINT user_subscriptions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  workout_id uuid,
  duration_minutes integer NOT NULL,
  calories_burned numeric NOT NULL,
  completed_at timestamp with time zone DEFAULT now(),
  log_date date DEFAULT CURRENT_DATE,
  CONSTRAINT workout_logs_pkey PRIMARY KEY (id),
  CONSTRAINT workout_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT workout_logs_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(id)
);
CREATE TABLE public.workouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  category text NOT NULL,
  muscle_group text,
  duration_minutes integer NOT NULL,
  difficulty text DEFAULT 'beginner'::text CHECK (difficulty = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  calories_per_minute numeric DEFAULT 5.0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  gym_id uuid,
  created_by uuid,
  day_of_week text,
  instructions text,
  updated_at timestamp with time zone DEFAULT now(),
  assigned_to uuid,
  is_personal boolean DEFAULT false,
  sets integer DEFAULT 3,
  reps integer DEFAULT 12,
  body_part text CHECK (body_part = ANY (ARRAY['chest'::text, 'back'::text, 'legs'::text, 'shoulders'::text, 'arms'::text, 'core'::text, 'full_body'::text, 'cardio'::text])),
  video_url text,
  CONSTRAINT workouts_pkey PRIMARY KEY (id),
  CONSTRAINT workouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT workouts_gym_fkey FOREIGN KEY (gym_id) REFERENCES public.gyms(id)
);
CREATE TABLE public.xp_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  amount integer NOT NULL,
  reason text NOT NULL,
  reference_id uuid,
  reference_type text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xp_transactions_pkey PRIMARY KEY (id)
);